// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Ping(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function Version():Promise<string>;
