// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appstate} from '../models';

export function Delete(arg1:Array<string>):Promise<void>;

export function Export(arg1:string):Promise<string>;

export function List(arg1:string):Promise<Array<appstate.FileEntry>>;

export function NewFolder(arg1:string,arg2:string):Promise<void>;

export function Rename(arg1:string,arg2:string):Promise<void>;
