// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['bind']['Files']['Delete'](arg1);
}

export function Export(arg1) {
  return window['go']['bind']['Files']['Export'](arg1);
}

export function List(arg1) {
  return window['go']['bind']['Files']['List'](arg1);
}

export function NewFolder(arg1, arg2) {
  return window['go']['bind']['Files']['NewFolder'](arg1, arg2);
}

export function Rename(arg1, arg2) {
  return window['go']['bind']['Files']['Rename'](arg1, arg2);
}
