// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MediaURL(arg1, arg2) {
  return window['go']['bind']['Preview']['MediaURL'](arg1, arg2);
}

export function Revoke(arg1) {
  return window['go']['bind']['Preview']['Revoke'](arg1);
}

export function ThumbURL(arg1) {
  return window['go']['bind']['Preview']['ThumbURL'](arg1);
}
