// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MediaURL(arg1:string,arg2:string):Promise<string>;

export function Revoke(arg1:string):Promise<void>;

export function ThumbURL(arg1:string):Promise<string>;
