// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseCacheDir():Promise<string>;

export function ChooseSyncDir():Promise<string>;

export function Get():Promise<Record<string, any>>;

export function SetAutoLock(arg1:number):Promise<void>;

export function SetCache(arg1:number,arg2:string):Promise<void>;

export function SetFontSize(arg1:number):Promise<void>;

export function SetMaxCores(arg1:number):Promise<void>;

export function SetSyncDir(arg1:string):Promise<void>;

export function SetTheme(arg1:number):Promise<void>;

export function SetTransfer(arg1:number,arg2:number):Promise<void>;

export function SyncNow():Promise<number>;
