// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseSyncDir() {
  return window['go']['bind']['Settings']['ChooseSyncDir']();
}

export function Get() {
  return window['go']['bind']['Settings']['Get']();
}

export function SetAutoLock(arg1) {
  return window['go']['bind']['Settings']['SetAutoLock'](arg1);
}

export function SetCache(arg1, arg2) {
  return window['go']['bind']['Settings']['SetCache'](arg1, arg2);
}

export function SetFontSize(arg1) {
  return window['go']['bind']['Settings']['SetFontSize'](arg1);
}

export function SetSyncDir(arg1) {
  return window['go']['bind']['Settings']['SetSyncDir'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['bind']['Settings']['SetTheme'](arg1);
}

export function SetTransfer(arg1, arg2) {
  return window['go']['bind']['Settings']['SetTransfer'](arg1, arg2);
}

export function SyncNow() {
  return window['go']['bind']['Settings']['SyncNow']();
}
