// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appstate} from '../models';

export function CancelAll():Promise<void>;

export function ClearFinished():Promise<void>;

export function Download(arg1:Array<appstate.FileEntry>,arg2:string):Promise<void>;

export function DownloadDialog():Promise<string>;

export function Retry(arg1:number):Promise<void>;

export function Tasks():Promise<Array<appstate.TaskView>>;

export function Upload(arg1:Array<string>,arg2:string):Promise<void>;

export function UploadDialog():Promise<Array<string>>;
