// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAll() {
  return window['go']['bind']['Transfer']['CancelAll']();
}

export function ClearFinished() {
  return window['go']['bind']['Transfer']['ClearFinished']();
}

export function Download(arg1, arg2) {
  return window['go']['bind']['Transfer']['Download'](arg1, arg2);
}

export function DownloadDialog() {
  return window['go']['bind']['Transfer']['DownloadDialog']();
}

export function Retry(arg1) {
  return window['go']['bind']['Transfer']['Retry'](arg1);
}

export function Tasks() {
  return window['go']['bind']['Transfer']['Tasks']();
}

export function Upload(arg1, arg2) {
  return window['go']['bind']['Transfer']['Upload'](arg1, arg2);
}

export function UploadDialog() {
  return window['go']['bind']['Transfer']['UploadDialog']();
}
