// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activity() {
  return window['go']['bind']['Vault']['Activity']();
}

export function BaiduAuthURL(arg1, arg2) {
  return window['go']['bind']['Vault']['BaiduAuthURL'](arg1, arg2);
}

export function BaiduClearAuth() {
  return window['go']['bind']['Vault']['BaiduClearAuth']();
}

export function BaiduSaveAuth(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bind']['Vault']['BaiduSaveAuth'](arg1, arg2, arg3, arg4, arg5);
}

export function BaiduStatus() {
  return window['go']['bind']['Vault']['BaiduStatus']();
}

export function ChooseLocalDir() {
  return window['go']['bind']['Vault']['ChooseLocalDir']();
}

export function ConnectOtherVault(arg1, arg2) {
  return window['go']['bind']['Vault']['ConnectOtherVault'](arg1, arg2);
}

export function ForgetRecent(arg1) {
  return window['go']['bind']['Vault']['ForgetRecent'](arg1);
}

export function ListOtherVaults() {
  return window['go']['bind']['Vault']['ListOtherVaults']();
}

export function Lock() {
  return window['go']['bind']['Vault']['Lock']();
}

export function Open(arg1) {
  return window['go']['bind']['Vault']['Open'](arg1);
}

export function RecentVaults() {
  return window['go']['bind']['Vault']['RecentVaults']();
}

export function RegenerateRecoveryCode(arg1) {
  return window['go']['bind']['Vault']['RegenerateRecoveryCode'](arg1);
}

export function RenameVault(arg1) {
  return window['go']['bind']['Vault']['RenameVault'](arg1);
}

export function RequestStats() {
  return window['go']['bind']['Vault']['RequestStats']();
}

export function ResumePending() {
  return window['go']['bind']['Vault']['ResumePending']();
}

export function State() {
  return window['go']['bind']['Vault']['State']();
}
