// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bind} from '../models';
import {appstate} from '../models';

export function Activity():Promise<void>;

export function BaiduAuthURL(arg1:string,arg2:string):Promise<string>;

export function BaiduClearAuth():Promise<void>;

export function BaiduSaveAuth(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function BaiduStatus():Promise<bind.BaiduAuthInfo>;

export function ChooseLocalDir():Promise<string>;

export function ConnectOtherVault(arg1:string,arg2:string):Promise<void>;

export function ForgetRecent(arg1:string):Promise<void>;

export function ListOtherVaults():Promise<Array<string>>;

export function Lock():Promise<void>;

export function Open(arg1:appstate.OpenRequest):Promise<appstate.OpenVaultResult>;

export function RecentVaults():Promise<Array<Record<string, any>>>;

export function RegenerateRecoveryCode(arg1:string):Promise<string>;

export function RenameVault(arg1:string):Promise<void>;

export function RequestStats():Promise<void>;

export function ResumePending():Promise<number>;

export function State():Promise<appstate.Snapshot>;
